basePath: /upc
host: 10.244.69.94:5051
info:
  contact: {email: mg@example.com, name: MG}
  description: Get product description and pricing
  title: UPC Lookup
  x-21-category: utilities
  x-21-keywords: [upc, pricing]
  x-21-total-price: {max: 2000, min: 2000}
  x-21-app-image: https://cdn.filepicker.io/api/file/L1qOBOudTWCFTvQXcM8S
  x-21-usage: 'Get product description, images and pricing information for a given Universal Product Code (UPC).'
  x-21-quick-buy: "Get product description and pricing by Universal Product Code (UPC):\n
  $21 buy \"http://10.244.69.94:5051/lookup?upc=078000147162\"\n\n
  Or download and run the upc client:\n
  $ wget -O upc.py http://10.244.69.94:5051/upc/client\n
  $ python3 upc.py 078000147162"

paths:
  /upc:
    get:
      summary: Get product information from UPC.
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      parameters: {upc: upc_code, description: UPC code, required: true, in: query, type: string}
      responses:
        '200':
          description: API responds successfully with Product desription and pricing.
          
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest
